application: signed-drakehs

# Version 1.0 (Alpha 2)
version: 1-0-a-2
api_version: 1
runtime: python27
threadsafe: true


handlers:

# Endpoints api
- url: /_ah/spi/.*
  script: server.application

# Student client page
- url: /s
  static_files: web_client/student.html
  upload: web_client/student.html

# Teacher client page
- url: /t
  static_files: web_client/teacher.html
  upload: web_client/teacher.html

# Web client resources
- url: /res/web_client
  static_dir: web_client/static
- url: /res/components
  static_dir: bower_components

# Main login/redirect page
- url: /.*
  static_files: web_client/index.html
  upload: web_client/index.html


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
